Nop.Plugin.DiscountRules.ShippingCountry/Models/RequirementModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.DiscountRules.ShippingCountry.Models
{
    public record RequirementModel
    {
        public RequirementModel()
        {
            AvailableCountries = new List<SelectListItem>();
        }

        public IList<SelectListItem> AvailableCountries { get; set; }

        [NopResourceDisplayName("Plugins.DiscountRules.ShippingCountry.Fields.Country")]
        public int CountryId { get; set; }

        public int DiscountId { get; set; }

        public int RequirementId { get; set; }
    }
}

Nop.Plugin.DiscountRules.ShippingCountry/Controllers/DiscountRulesShippingCountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core.Domain.Discounts;
using Nop.Plugin.DiscountRules.ShippingCountry.Models;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Discounts;
using Nop.Services.Localization;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.DiscountRules.ShippingCountry.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    [AutoValidateAntiforgeryToken]
    public class DiscountRulesShippingCountryController : BasePluginController
    {
        #region Fields

        private readonly ICountryService _countryService;
        private readonly IDiscountService _discountService;
        private readonly ILocalizationService _localizationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;        

        #endregion

        #region Ctor

        public DiscountRulesShippingCountryController(ICountryService countryService,
            IDiscountService discountService,
            ILocalizationService localizationService,
            IPermissionService permissionService,
            ISettingService settingService)
        {           
            _countryService = countryService; 
            _discountService = discountService;
            _localizationService = localizationService;            
            _permissionService = permissionService;
            _settingService = settingService;
        }

        #endregion

        #region Methods

        public async Task<IActionResult> Configure(int discountId, int? discountRequirementId)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageDiscounts))
                return Content("Access denied");

            var discount = await _discountService.GetDiscountByIdAsync(discountId);

            if (discount == null)
                throw new ArgumentException("Discount could not be loaded");

            DiscountRequirement discountRequirement = null;

            if (discountRequirementId.HasValue)
            {
                discountRequirement = await _discountService.GetDiscountRequirementByIdAsync(discountRequirementId.Value);
                if (discountRequirement == null)
                    return Content("Failed to load requirement.");
            }

            var shippingCountryId = await _settingService.GetSettingByKeyAsync<int>(string.Format(DiscountRequirementDefaults.SETTINGS_KEY, discountRequirementId ?? 0));

            var model = new RequirementModel
            {
                RequirementId = discountRequirementId ?? 0,
                DiscountId = discountId,
                CountryId = shippingCountryId
            };

            //countries
            model.AvailableCountries.Add(new SelectListItem { Text = await _localizationService.GetResourceAsync("Plugins.DiscountRules.ShippingCountry.Fields.SelectCountry"), Value = "0" });

            foreach (var c in await _countryService.GetAllCountriesAsync(showHidden: true))
                model.AvailableCountries.Add(new SelectListItem { Text = c.Name, Value = c.Id.ToString(), Selected = discountRequirement != null && c.Id == shippingCountryId });

            //add a prefix
            ViewData.TemplateInfo.HtmlFieldPrefix = string.Format(DiscountRequirementDefaults.HTML_FIELD_PREFIX, discountRequirementId ?? 0);

            return View("~/Plugins/DiscountRules.ShippingCountry/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(RequirementModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageDiscounts))
                return Content("Access denied");

            if (ModelState.IsValid)
            {
                //load the discount
                var discount = await _discountService.GetDiscountByIdAsync(model.DiscountId);
                if (discount == null)
                    return NotFound(new { Errors = new[] { "Discount could not be loaded" } });

                //get the discount requirement
                var discountRequirement = await _discountService.GetDiscountRequirementByIdAsync(model.RequirementId);

                //the discount requirement does not exist, so create a new one
                if (discountRequirement == null)
                {
                    discountRequirement = new DiscountRequirement
                    {
                        DiscountId = discount.Id,
                        DiscountRequirementRuleSystemName = DiscountRequirementDefaults.SYSTEM_NAME
                    };

                    await _discountService.InsertDiscountRequirementAsync(discountRequirement);
                }

                await _settingService.SetSettingAsync(string.Format(DiscountRequirementDefaults.SETTINGS_KEY, discountRequirement.Id), model.CountryId);

                return Ok(new { NewRequirementId = discountRequirement.Id });
            }

            return BadRequest(new { Errors = GetErrorsFromModelState() });
        }

        #endregion

        #region Utilities

        private IEnumerable<string> GetErrorsFromModelState()
        {
            return ModelState.Values.SelectMany(v => v.Errors.Select(e => e.ErrorMessage));
        }

        #endregion
    }
}

Nop.Plugin.DiscountRules.ShippingCountry/Views/Configure.cshtml
@{
    Layout = "";
}
@model Nop.Plugin.DiscountRules.ShippingCountry.Models.RequirementModel

<script type="text/javascript">
        $(document).ready(function () {
            $('#saveshippingcountryrequirement@(Model.RequirementId)').click(function () {
                var countryId = $("#@Html.IdFor(model => model.CountryId)").val();
                var discountId = @Model.DiscountId;
                var requirementId = @Model.RequirementId;

                var postData = {
                    DiscountId: discountId,
                    RequirementId: requirementId,
                    CountryId: countryId
                };
                addAntiForgeryToken(postData);

                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "@(Url.Action("Configure", "DiscountRulesShippingCountry"))",
                    data: postData,
                    success: function (data, textStatus, jqXHR) {
                         $('#pnl-save-requirement-result@(Model.RequirementId)').fadeIn("slow").delay(1000).fadeOut("slow");
                         //notify parent if it's a new requirement
                         @if (Model.RequirementId == 0)
                         {
                            <text>$("#discountRequirementContainer").trigger('nopnewdiscountruleadded', [data.NewRequirementId]);</text>
                         }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        var $alertInfoEl = $("#saveshippingcountryrequirementAlert-info");
                        let response = jqXHR.responseJSON;
                        if (response instanceof Object && response.hasOwnProperty('Errors')) {
                            var errorMessages = '';
                            $.each(response.Errors, function (i, error) {
                                errorMessages += error;
                                if (response.Errors.length - 1 != i)
                                    errorMessages += '</br>';
                            });
                            $alertInfoEl.html(errorMessages);
                        } else {
                            // display default error
                            $alertInfoEl.html('@T("Admin.Promotions.Discounts.Requirements.FailedToSave")');
                        }

                        $("#saveshippingcountryrequirementAlert").click();
                    }
                });
            });
        });
</script>

<div class="form-group row">
    <div class="col-md-3 requirement-label-col">
        <nop-label asp-for="CountryId" />
    </div>
    <div class="col-md-9 requirement-data-col">
        <div class="requirement-data-input">
            <nop-select asp-for="CountryId" asp-items="Model.AvailableCountries" />
        </div>
        <div class="requirement-data-buttons">
            <input type="button" id="saveshippingcountryrequirement@(Model.RequirementId)" class="btn btn-primary" value="@T("Admin.Common.Save")" />
        </div>
    </div>
</div>
<div class="form-group row">
    <div class="col-md-offset-3 col-md-9 requirement-messages-col">
        <div id="pnl-save-requirement-result@(Model.RequirementId)" class="text-green margin-t-5" style="display: none;">
            @T("Admin.Promotions.Discounts.Requirements.Saved")
        </div>
    </div>
</div>
<nop-alert asp-alert-id="saveshippingcountryrequirementAlert" />

Nop.Plugin.DiscountRules.ShippingCountry/Views/DiscountRulesShippingCountry/Configure.cshtml
@{
    Layout = "";
}
@model Nop.Plugin.DiscountRules.ShippingCountry.Models.RequirementModel
@using Nop.Web.Framework;

    <script type="text/javascript">
        $(document).ready(function () {
            $('#saveshippingcountryrequirement@(Model.RequirementId)').click(function () {
                var countryId = $("#@Html.FieldIdFor(model => model.CountryId)").val();
                var discountId = @Model.DiscountId;
                var requirementId = @Model.RequirementId;
                
                var postData = {
                    discountId: discountId, 
                    discountRequirementId: requirementId, 
                    countryId: countryId
                };
                addAntiForgeryToken(postData);


                $.ajax({
                    cache:false,
                    type: "POST",
                    url: "@(Url.Action("Configure", "DiscountRulesShippingCountry"))",
                    data: postData,
                    success: function (data) {
                         $('#pnl-save-requirement-result@(Model.RequirementId)').fadeIn("slow").delay(1000).fadeOut("slow");
                         //notify parent if it's a new requirement
                         @if (Model.RequirementId == 0)
                         {
                            <text>$("#discountRequirementContainer").trigger('nopnewdiscountruleadded', [data.NewRequirementId]);</text>
                         }
                    },
                    error:function (xhr, ajaxOptions, thrownError){
                        alert('@Html.Raw(HttpUtility.JavaScriptStringEncode(T("Admin.Promotions.Discounts.Requirements.FailedToSave").Text))');
                    }  
                });
            });
        });
    </script>

<div class="form-group">
    <div class="col-md-3">
        @Html.NopLabelFor(model => model.CountryId)
    </div>
    <div class="col-md-9">
        @Html.NopDropDownListFor(model => model.CountryId, Model.AvailableCountries)
        <div id="pnl-save-requirement-result@(Model.RequirementId)" style="display: none;">
            @T("Admin.Promotions.Discounts.Requirements.Saved")
        </div>
    </div>
</div>
<div class="form-group">
    <div class="col-md-9 col-md-offset-3">
        <input type="button" id="saveshippingcountryrequirement@(Model.RequirementId)" class="btn btn-primary" value="@T("Admin.Common.Save")" />
    </div>
</div>